const router = require("express").Router();
const controller = require("../controller/cartController");
const asyncHandler = require("../utils/asyncHandler");
const { Authentication, requireRoles } = require("../middleware/auth");
router.use(Authentication, requireRoles("student"));
router.get("/", asyncHandler(controller.get));
router.post("/add/:courseId", asyncHandler(controller.add));
router.delete("/remove/:courseId", asyncHandler(controller.remove));
router.delete("/clear", asyncHandler(controller.clear));
module.exports = router;
